### ISSUE TITLE
Trying to submit crash dumps but instead get "I'm a teapot"

### ISSUE THREAD

**Issue by tenent007963** [pmmp/CrashArchive#20]
Was trying to submit multiple crash dumps but all returns Error 418: I'm a teapot.
UsingChrome Version 75.0.3770.100

And here's the crash dumps:
[Wed_Jul_17-09.28.59-UTC_2019.log](https://pastebin.com/sTVfULQR)
[Wed_Jul_17-07.26.10-UTC_2019.log](https://pastebin.com/BSRmZNR9)

**Comment by dktapps** [comment]
Your server is running a blacklisted plugin.

**Comment by tenent007963** [comment]
Uh can I ask where to find a list of "Blacklisted plugins"?

**Comment by SOF3** [comment]
This doesn't really matter. This just means certain plugins do unstable stuff so much that it crashes all the time and we decide to ignore them. It doesn't really affect users, since we are simply refusing to accept such crash reports, but this won't make your server crash more or crash less.
