### ISSUE TITLE
Installing fails 

### ISSUE THREAD

**Issue by belohnung** [pmmp/CrashArchive#21]
I get those errors 
`root@v1754 ~/ca-pmmp/src/github.com/pmmp/CrashArchive # make build/linux
GOOS=linux go build -o ./bin/ca-pmmp-linux
main.go:10:2: cannot find package "github.com/pmmp/CrashArchive/app" in any of:
        /usr/lib/go-1.7/src/github.com/pmmp/CrashArchive/app (from $GOROOT)
        ($GOPATH not set)
main.go:11:2: cannot find package "github.com/pmmp/CrashArchive/app/crashreport" in any of:
        /usr/lib/go-1.7/src/github.com/pmmp/CrashArchive/app/crashreport (from $GOROOT)
        ($GOPATH not set)
main.go:12:2: cannot find package "github.com/pmmp/CrashArchive/app/database" in any of:
        /usr/lib/go-1.7/src/github.com/pmmp/CrashArchive/app/database (from $GOROOT)
        ($GOPATH not set)
main.go:13:2: cannot find package "github.com/pmmp/CrashArchive/app/router" in any of:
        /usr/lib/go-1.7/src/github.com/pmmp/CrashArchive/app/router (from $GOROOT)
        ($GOPATH not set)
main.go:14:2: cannot find package "github.com/pmmp/CrashArchive/app/template" in any of:
        /usr/lib/go-1.7/src/github.com/pmmp/CrashArchive/app/template (from $GOROOT)
        ($GOPATH not set)
main.go:15:2: cannot find package "github.com/pmmp/CrashArchive/app/webhook" in any of:
        /usr/lib/go-1.7/src/github.com/pmmp/CrashArchive/app/webhook (from $GOROOT)
        ($GOPATH not set)
Makefile:10: recipe for target 'build/linux' failed
make: *** [build/linux] Error 1`

**Comment by dktapps** [comment]
The error is self-explanatory, your GOPATH is undefined. You haven't followed the proper instructions on the README.
