### ISSUE TITLE
Crash on Start up (with a Crashdump)

### ISSUE THREAD

**Issue by Khaogamermain01** [pmmp/CrashArchive#22]
### Issue description
The server crashes and makes a crash dump

### Steps to reproduce the issue
1. Do the steps of setting up the server
2. starting the server

### OS and version
* PocketMine-MP: 3.16.0
* Server OS: Macbook Air
* Game version: PE/Win 10

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded? Yes

### Crashdump, backtrace or other files
https://crash.pmmp.io/view/4658933

**Comment by Khaogamermain01** [comment]
![Uploading Screen Shot 2563-11-23 at 21.07.14.png…]()

**Comment by Khaogamermain01** [comment]
![Uploading Screen Shot 2563-11-23 at 21.08.13.png…]()

**Comment by Khaogamermain01** [comment]
[Hi](Khao.pocketmc.net)

**Comment by dktapps** [comment]
You're trying to run two servers on the same port.
