### ISSUE TITLE
Change the crash types shown in the list of crashes.

### ISSUE THREAD

**Issue by nathfreder** [pmmp/CrashArchive#4]
The list of crashes (as seen [here](https://crash.pmmp.io/list)) should not include crashes that were caused solely by a plugin; if someone were to go looking through the list so that they can make a pull request to fix the issue, it would make no sense to include the crashes caused by plugins on the list. The user should have an option to view the following at a time.

1. Plugin Crashes Only
2. Software Crashes Only to to
3. Plugin and Software Crashes

I plan on making a pull request implementing this change if it is accepted. What are your thoughts on this change?

**Comment by dktapps** [comment]
On the contrary. The crash archive is expected to be used by plugin developers to fix their creations, as described on the homepage.

Better filters and searching have been planned for a long time.

**Comment by nathfreder** [comment]
I see that now.

**Comment by nathfreder** [comment]
Closing due to the fact that this is irrelevant.

**Comment by SOF3** [comment]
It would be better if developers can search for a substring in the stack trace.
